### ISSUE TITLE
[feature] add tick marks on sliders

### ISSUE THREAD

**Issue by tetraf** [Siot/PaWebControl#1]
Not already supported by all Web browsers (not [in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=841942) for example) but, with the HTML attribute `list` and the `<datalist>` tag, it should be possible to add tick marks to sliders for some values (ie: 100%). What do you think of that?

**Comment by Siot** [comment]
Added tick for 100%. [See compatibility status](http://caniuse.com/#feat=datalist).
